### ISSUE TITLE
Broken UI using TiddlyDesktop with WikiFolder

### ISSUE THREAD

**Issue by ualich** [Jermolene/TiddlyDesktop#184]
While running a wiki on TiddlyDesktop directly from WikiFolder a strange user interface bug appears.

Some toolbar buttons fail to be displayed although the HTML behind them is rendered correctly. What is strange about that is that only some buttons are not displaying and I couldn't find any pattern associated with it. Also eg. delete button displays in editor toolbar but not in tiddler controls toolbar.

What is triggering the problem is the filter `[<listItem>encodeuricomponent[]addprefix[tc-btn-]]` in tiddlers:

* `$:/core/ui/Buttons/more-tiddler-actions`
* `$:/core/ui/PageTemplate/pagecontrols`
* `$:/core/ui/ViewTemplate/title`

Thus deleting the filter solves the problem and (as it seems to me) no functionality is lost (the HTML elements just lack one tag, which I don't even undestand what is the purpose of?).

Connecting to the same wiki on Chrome or Firefox also eliminates the problem, so I suspect it is a NWJS specific thing. It is also WikiFolder specific as the problem does not occur with WikiFiles.

I am aware my solution is suboptimal and may break some other part, so I am putting it out here for proper assesment.

Some additional info:

* TiddlyDesktop v0.0.14
* TiddlyWiki v5.1.22
* NWJS v0.43.3-sdk
* System: Ubuntu 18.04

**Comment by Jermolene** [comment]
Hi @urbanalich the filter `[<listItem>encodeuricomponent[]addprefix[tc-btn-]]` is used to generate a CSS class that is assigned to the button so that users can easily target specific buttons with CSS.

I notice that you're using NWJS v0.43.3 rather than the v0.33.3 version that is bundled with TiddlyDesktop; do you still get the problem if you revert to the stock TiddlyDesktop distribution?

**Comment by urbanalich** [comment]
Yes, the same thing on the bundled version, that's why I bothered upgrading.

I have limited knowledge but I suspect it is some character sequence created while encoding that has some unexpected effect. If anyone is able to notice some pattern I'm providing the list of buttons not showing:

**Page toolbar**:

* new tiddler
* new journal
* new image
* import
* tiddler manager


**View toolbar**:

* new here
* new journal here
* clone
* edit
* delete

Just to be clear - by not showing I mean they behave as there would be CSS `display: none;` assigned to them. If I specifically set `display: inline;` that also works though not for the more tiddler actions popup.

**Comment by BramChen** [comment]
@Jermolene 
It seems pretty obvious, the read-only mode is engaged.

**Comment by Jermolene** [comment]
Thanks @BramChen! Can you send a PR with the changes?

**Comment by BramChen** [comment]
@Jeremy I'd sent a PR.
