### ISSUE TITLE
Allow multiple instances to run at once

### ISSUE THREAD

**Issue by Jermolene** [Jermolene/TiddlyDesktop#47]
It would be useful to be able to run two instances of TiddlyDesktop (with separate configuration) for separating work and personal wikis.

See discussion here:

https://groups.google.com/d/topic/tiddlywiki/3f697_QBzSw/discussion

**Comment by mklauber** [comment]
I believe this is currently possible, if you pass the `--data-path` flag as follows.

`./nw --data-path="path-to-new-config-dir"`

**Comment by croulibri** [comment]
Maybe it could be relevant to update the first page instruction because I understand that the data-path flag has been replaced by user-data-dir (see http://docs.nwjs.io/en/latest/References/Command%20Line%20Options/#-user-data-dir )

Or at least the data-path flag is not working for me (windows 7 and TiddlyDesktop 0.0.9) but user-data-dir does

**Comment by Jermolene** [comment]
Thanks @croulibri, I've pushed an update.
