### ISSUE TITLE
TiddlyDesktop includes TiddlyWiki Classic source files

### ISSUE THREAD

**Issue by KarelWintersky** [Jermolene/TiddlyDesktop#61]
Too old files for TW2 Core:

`.\tiddlywiki\editions\tw2\source\tiddlywiki\`

Actual version is 2.7.0, but in `/tiddlywiki/editions/tw2/source/tiddlywiki/js/Version.js`  is
`var version = {title: "TiddlyWiki", major: 2, minor: 6, revision: 5, date: new Date("October 6, 2011"), extensions: {}};
`

**Comment by KarelWintersky** [comment]
I use latest version, downloaded from release branch.

**Comment by Jermolene** [comment]
Hi @KarelWintersky those files are actually part of the TiddlyWiki5 repo:

https://github.com/Jermolene/TiddlyWiki5/tree/master/editions/tw2

The file is test data for testing the procedure of building TW2 from it's components using TW5. So it's not important that it's the very latest version of TW2.

**Comment by pmario** [comment]
IMO it shouldn't be there anymore. We should find a way to get rid of it. It is distributed with npm, git clone, ... 

And it is the main reason, why github thinks TW is an HTML and not javascript application. 
see: https://github.com/Jermolene/TiddlyWiki5/search?l=html&p=1  imo this hurts popularity a lot. 

We are on page 3 of the most starred projects: https://github.com/stars?direction=desc&page=3&sort=stars

If someone filters for javascript, we should be on page 2, but we are not there, because github lists us at html, which has only 4 project, nobody cares. 
https://github.com/stars?direction=desc&language=javascript&page=2&sort=stars

**Comment by Jermolene** [comment]
> And it is the main reason, why github thinks TW is an HTML and not javascript application

Ah, that makes sense.

I agree we should get rid of them, I'll do so now so that they are out of the way for 5.1.9.

**Comment by Jermolene** [comment]
Now fixed:

https://github.com/Jermolene/TiddlyWiki5/commit/3ed5c92361ff4f6685acdfd46b5a47426ae6ce58

![screenshot 2015-06-16 19 53 10](https://cloud.githubusercontent.com/assets/174761/8191685/6ab0c978-1461-11e5-9660-85faab800d6a.png)

**Comment by pmario** [comment]
Yea. So for npm it should be a bit more light weight too :)

**Comment by KarelWintersky** [comment]
@Jermolene is there any old TW2 repo?

TiddlyWiki5 is tooo new for me :( Unfamiliar design, etc etc.

**Comment by pmario** [comment]
https://github.com/TiddlyWiki/tiddlywiki

**Comment by Jermolene** [comment]
@KarelWintersky TW2 itself now lives at http://classic.tiddlywiki.com/

**Comment by KarelWintersky** [comment]
@Jermolene core 2.8.1 ? Cool! Thanx!

**Comment by Jermolene** [comment]
Fixed in v0.0.5
