### ISSUE TITLE
Confusing feature in internals

### ISSUE THREAD

**Issue by danielo515** [Jermolene/TiddlyDesktop#62]
> TiddlyDesktop is itself an instance of TiddlyWiki, configured to run as a hybrid of the Node.js configuration and the browser-based configuration. It uses the Node.js file APIs to synchronise individual tiddler files to the file system while also rendering a user interface in the "backstage" window.

This is confusing. It makes me think that it is possible to have wikis that saves individual tiddlers to the file-system, but this is only possible for the backstage TW. Or maybe it is available for any TW? A bit more of info in this area would be useful.

Regards

**Comment by pmario** [comment]
Every TW has the possibility to save single tiddlers as files.

The only problem is: If you put an empty TW into a directory full of tiddlers, it can't read them, since a browser doesn't allow you read the directory to list the files. So you would need to know all tiddler names up front and hardcode them into the emtpy tw. Which makes it pretty useless for general purpose. 

If you use a NW.js this limitation is not there, since you can access the nodejs file api. The backside is. It's a big security hole if you run untrusted content, since nodejs has full access to your harddisk.

**Comment by Jermolene** [comment]
Hi @danielo515 you're right that saving tiddlers as single files is currently restricted to the backstage wiki. The plan is indeed to extend that functionality to wikis hosted within TiddlyDesktop.

**Comment by danielo515** [comment]
Thank you for clarifying it. 

Regards
